SignRequestExpress/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SignRequestExpress.Controllers
{
    [AllowAnonymous]
    public class DefaultController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

SignRequestExpress/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SignRequestExpress.Models;

namespace SignRequestExpress.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            //ViewData["Message"] = "Your application description page.";

            return View();
        }

        [HttpGet]
        public IActionResult Contact()
        {
            //ViewData["Message"] = "Your contact page.";

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Contact(ContactModel model)
        {
            // Compose Email
            using(var message = new MailMessage(model.Email, "michael.poust221@gmail.com"))
            {
                message.To.Add(new MailAddress("michael.poust221@gmail.com"));
                message.From = new MailAddress(model.Email);
                message.Subject = model.Subject;
                message.Body = model.Message;
                

                using (var smtpClient = new SmtpClient("smtp.gmail.com", 587))
                {
                    try
                    {
                        smtpClient.EnableSsl = true;
                        smtpClient.Send(message);
                        return RedirectToAction(nameof(HomeController.EmailSent), "Home");
                    }
                    catch (Exception ex)
                    {
                        //ViewData["email"] = ex.ToString();
                        ViewData["email"] = "Unable to send email at this time. Please direct any questions to the developer at - michael.poust221@gmail.com";
                        //return RedirectToAction(nameof(HomeController.EmailSentError), "Home");
                    }
                }
            }
            // If we got this far something went wrong, redisplay form
            return View();
        }

        public IActionResult EmailSent()
        {
            return View();
        }

        public IActionResult EmailSentError()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Help()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SignRequestExpress/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About SRE";
}

<br />

<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p><i>To view the full project proposal for SRE visit this <a href="https://www.dropbox.com/s/p3mwc0e2k1wf9gr/cit498-proposal-final_mpoust.pdf?dl=0" class="dark-links" target="_blank">DropBox</a> link. If this doesn't answer your question feel free to contact the developer at michael.poust221@gmail.com</i></p>

<p>Sign Request Express, "SRE," is created by Michael Poust for his Fall 2018 Senior Project 
    class (CIT498) at the Pennsylvania College of Technology.</p>

<p>To see what SRE can do, feel free to test the Demo accounts listed below in the format of 'Username / Password'</p>
<ul>
    <li>DemoSales1 / Password123!</li>
    <li>DemoSales2 / Password123!</li>
    <li>DemoManager / Password123!</li>
    <li>DemoSignShop / Password123!</li>
</ul>

<p>There are three (3) account types to SRE. The Sales users can submit sign requests, and track their production. The Manager users can approve submitted requests for production which then places the request in a queue for the Sign Shop users who may then process the requests by entering them into the print queue or marking them as printed. When marked as printed the Sales associates may pick up their requests for delivery.</p>

SignRequestExpress/Views/Home/Contact.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@model SignRequestExpress.Models.ContactModel

@{
    ViewData["Title"] = "Contact us";
}

<br />

<h2>@ViewData["Title"]</h2>


<!--
    <address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>
-->
<!-- TODO: Add Contact form - use Lynda as inspiration -->
<!--
    <address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>
-->

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Send an email with your question</h5>
    </div>
    <div class="card-body local-card-body">
        <form asp-controller="Home" asp-action="Contact" method="post" novalidate class="needs-validation">
            <br />
            <div class="form-group row">
                <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-6">
                    <input type="text" asp-for="Name" class="form-control" placeholder="Your Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Email" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-6">
                    <input type="email" asp-for="Email" class="form-control" placeholder="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Subject" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-6">
                    <input type="text" asp-for="Subject" class="form-control" placeholder="Subject"/>
                    <span asp-validation-for="Subject" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Message" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-6">
                    <textarea asp-for="Message" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Message" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-6">
                    <button class="btn btn-orange" type="submit">Send Message</button>
                </div>
            </div>
        </form>
    </div>
</div>

@ViewData["email"]

SignRequestExpress/Views/Home/EmailSent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

@{
    ViewData["Title"] = "Request Submitted";
    Layout = "_Layout";
}

<br />

<div class="alert alert-success" role="alert">
    <h4>Email Sent Successfully</h4>
    <p>
        <a asp-controller="Home" asp-action="Index" class="alert-link">Click Here</a> to return Home.
    </p>
</div>

SignRequestExpress/Views/Home/EmailSentError.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

@{
    ViewData["Title"] = "Request Submitted";
    Layout = "_Layout";
}

<br />

<!--
<div class="alert" role="alert">
    <h4>Request Submitted Successfully</h4>
    <p>
        <a asp-controller="Sales" asp-action="Index" class="alert-link">Click Here</a> to return to your dashboard.
    </p>
</div>
    -->

<div class="alert alert-danger" role="alert">
    <h4>Error Sending Email</h4>
    <p>
        <a asp-controller="Home" asp-action="Index" class="alert-link">Click Here</a> to return Home.
    </p>
</div>

SignRequestExpress/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Home";
}

<!--
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
    -->

<br />

<div class="jumbotron">
    <div class="container">
        <img src="~/images/logo.svg" class="image-fluid home-image" alt="image test" />

        <hr class="my-4" />
        <p>This application is created by Michael Poust for his Software Development senior project, during the Fall 2018 semester. See the <a asp-area="" asp-controller="Home" asp-action="About" class="dark-links">'About'</a> page to learn more.</p>
    </div>

    @if (SignInManager.IsSignedIn(User))
    {
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Dashboard</h5>
                        <p class="card-text">Return to your dashboard to continue optimizing your Sign Request workflow.</p>
                        @if (User.IsInRole("Sales"))
                        {
                            <a asp-controller="Sales" asp-action="Index" class="btn btn-orange">Dashboard</a>
                        }
                        else if (User.IsInRole("Executive"))
                        {
                            <a asp-controller="Executive" asp-action="Index" class="btn btn-orange">Dashboard</a>

                        }
                        else if (User.IsInRole("Administrator"))
                        {
                            <a asp-controller="Administrator" asp-action="Index" class="btn btn-orange">Dashboard</a>
                        }
                        else if (User.IsInRole("SignShop"))
                        {
                            <a asp-controller="SignShop" asp-action="Index" class="btn btn-orange">Dashboard</a>
                        }
                        else
                        {
                            <a asp-controller="Default" asp-action="Index" class="btn btn-orange">Dashboard</a>
                        }
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Have a problem?</h5>
                        <p class="card-text">Visit the <a asp-area="" asp-controller="Home" asp-action="Help" class="dark-links">'Help'</a> page for common issues or fill out the contact form with your problem.</p>
                        <a asp-controller="Home" asp-action="Contact" class="btn btn-orange">Contact</a>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Get started</h5>
                        <p class="card-text">Register an account to start optimizing your Sign Request workflow.</p>
                        <a asp-controller="Account" asp-action="Register" class="btn btn-orange">Register</a>

                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Have an account?</h5>
                        <p class="card-text">Login to access your dashboard and explore the many features of your account.</p>
                        <a asp-controller="Account" asp-action="Login" class="btn btn-orange">Login</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <br />
            <!--TODO: Make subject auto fill when accessed from this link-->
            <p>Want SRE at your organization? Fill out the <a asp-controller="Home" asp-action="Contact" class="dark-links">'Contact'</a> form to receive more information.</p>
        </div>


        
    }
</div>